### ISSUE TITLE
Bug for total inflow/outflow calculation.

### ISSUE THREAD

**Issue by KN-CY** [AY2223S2-CS2113T-T09-1/tp#149]
Eg. when amount is given as 3.51499999999999999.... It gets converted to 2d.p. when displayed in view table. But the actual variable holding the value is in float which represents more than 2d.p. This could result in imprecision when calculating total outflow/inflow.

![image](https://user-images.githubusercontent.com/78925549/226556754-a884c548-da91-4f57-bdb2-64409cbcbc3a.png)
In the above example, `test 2` is added with the following command `add -out -d test 2 $3.51499999999` and is thus rounded down to $3.51 in the table.

But when calculating total outflow, the more precise float value of > 2d.p. is used, leading to inaccuracies when calculating total outflow as 3.50 + 1.50 + 3.51 * 5 = 22.55 < 22.57

**Comment by BenjaminPoh** [comment]
Should we just round all value to 2dp at input?
