### ISSUE TITLE
Possible bug with printing budget exceeded

### ISSUE THREAD

**Issue by KN-CY** [AY2223S2-CS2113T-T09-1/tp#247]
When deleting a financial statement, a print is done to state that budget is exceeded. Not sure if this is intended

![image](https://user-images.githubusercontent.com/78925549/228550275-28e13094-3a56-44c4-9ddb-8a583e7988ef.png)

**Comment by BenjaminPoh** [comment]
Intended if the budget is still exceeded and if deletion is on an entry that is in the same month/year as the user
Will update together with #248
