### ISSUE TITLE
[PE-D][Tester C] Documentation Bug: Ascending order

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113T-T09-1/tp#294]
Userguide:

![image.png](https://raw.githubusercontent.com/WilsonLee2000/ped/main/files/f8fd361e-f24f-4ec8-8254-a228e4023d91.png)

Code tryout:

![image.png](https://raw.githubusercontent.com/WilsonLee2000/ped/main/files/50954972-0e28-4763-a166-3c6132c39cdc.png)

The ascending order in the documentation is not clearly documented in detailed, is it ascending order based on the amount? Ascending order based on the date? Or ascending order based on the index? I'm unable to determine and understand it. 

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: WilsonLee2000/ped#2

**Comment by BenjaminPoh** [comment]
To update "ascending order of absolute value"
