### ISSUE TITLE
[PE-D][Tester D] Shortcut command not working?

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113T-T09-1/tp#311]
see sample input:
```
> shortcut a -maps add
Shortcut successfully added

> a -in Salary $100
Sorry! I do not understand your input!

```
There doesn't seem to be anything stopping me from creating shortcut `a` to map to `add`, however I think the feature is meant to replace whole commands so it doesn't work.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: choongzhanhong/ped#7

**Comment by KN-CY** [comment]
Such a feature is not intended as a shortcut should map a full command rather than part of it.
