### ISSUE TITLE
[PE-D][Tester B] Invalid characters defaulting to "?"

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113T-T09-1/tp#313]
![image.png](https://raw.githubusercontent.com/MingEn82/ped/main/files/6a81182a-fdb1-4841-93c7-3348e1fb82b0.png)

When unknown characters are given, they default to "?", which results in these results appearing when `filter -d ?` is ran

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: MingEn82/ped#8

**Comment by azriellee** [comment]
CMD only takes in ASCII characters, we can change it to only accept ascii
