### ISSUE TITLE
[PE-D][Tester A] Commands taking indexes give invalid error message when transaction list is empty

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113T-T09-1/tp#327]
![image.png](https://raw.githubusercontent.com/ERJUNZE/ped/main/files/d93fc4e4-c183-4b96-b463-59a95cd489ec.png)

The error message asks for an index > 0 and <= 0, which is impossible

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: ERJUNZE/ped#7

**Comment by lil1n** [comment]
same for delete
