### ISSUE TITLE
UG understandingCLI image missing

### ISSUE THREAD

**Issue by azriellee** [AY2223S2-CS2113T-T09-1/tp#373]
![image](https://user-images.githubusercontent.com/88471489/230350958-3312d328-b194-4e9d-b7df-b42c3b9fd4f3.png)
I think the person who updated this portion might have forgotten to stage and push the image file

**Comment by ChongQiRong** [comment]
![image](https://user-images.githubusercontent.com/88194809/230634304-816c14b1-daad-400c-ae52-4682f83036c4.png)
Seems to be working fine
